package GUI.Form;


public class FormHoaDon extends javax.swing.JPanel {
    public FormHoaDon() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textMahd = new javax.swing.JTextField();
        textMakh = new javax.swing.JTextField();
        textTienthanhtoan = new javax.swing.JTextField();
        javax.swing.JLabel labelMahd = new javax.swing.JLabel();
        javax.swing.JLabel labelManv = new javax.swing.JLabel();
        javax.swing.JLabel labelMakh = new javax.swing.JLabel();
        javax.swing.JLabel labelThanhtoan = new javax.swing.JLabel();
        textManv = new javax.swing.JTextField();
        javax.swing.JLabel labelNgaylap = new javax.swing.JLabel();
        textNgaylap = new javax.swing.JTextField();
        jLabelTthd = new javax.swing.JLabel();
        textMahd1 = new javax.swing.JTextField();
        textMakh1 = new javax.swing.JTextField();
        textThanhtien1 = new javax.swing.JTextField();
        javax.swing.JLabel labelMahd1 = new javax.swing.JLabel();
        javax.swing.JLabel labelManv1 = new javax.swing.JLabel();
        javax.swing.JLabel labelMakh1 = new javax.swing.JLabel();
        javax.swing.JLabel labelThanhtien1 = new javax.swing.JLabel();
        textManv1 = new javax.swing.JTextField();
        javax.swing.JLabel labelNgaylap1 = new javax.swing.JLabel();
        textNgaylap1 = new javax.swing.JTextField();
        javax.swing.JLabel labelTongtien = new javax.swing.JLabel();
        textTongtien = new javax.swing.JTextField();
        textTienkm = new javax.swing.JTextField();
        javax.swing.JLabel labelTienkm = new javax.swing.JLabel();
        javax.swing.JLabel labelTienkm1 = new javax.swing.JLabel();
        textTienkm1 = new javax.swing.JTextField();
        bntThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        bntXoa = new javax.swing.JButton();
        btnTim = new javax.swing.JButton();
        btnTailai = new javax.swing.JButton();
        jLabelCthd = new javax.swing.JLabel();
        bntThem1 = new javax.swing.JButton();
        btnSua1 = new javax.swing.JButton();
        bntXoa1 = new javax.swing.JButton();
        btnTim1 = new javax.swing.JButton();
        btnTailai1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableTthd = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableCthd = new javax.swing.JTable();

        setLayout(null);

        textMahd.setToolTipText("");
        add(textMahd);
        textMahd.setBounds(140, 40, 150, 24);

        textMakh.setToolTipText("");
        add(textMakh);
        textMakh.setBounds(140, 70, 150, 24);

        textTienthanhtoan.setToolTipText("");
        textTienthanhtoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textTienthanhtoanActionPerformed(evt);
            }
        });
        add(textTienthanhtoan);
        textTienthanhtoan.setBounds(140, 220, 150, 24);

        labelMahd.setText("Mã Hóa Đơn");
        add(labelMahd);
        labelMahd.setBounds(20, 40, 88, 18);

        labelManv.setText("Mã Nhân Viên");
        add(labelManv);
        labelManv.setBounds(20, 100, 150, 18);

        labelMakh.setText("Mã Khách Hàng");
        add(labelMakh);
        labelMakh.setBounds(20, 70, 140, 18);

        labelThanhtoan.setText("Tiền Thanh Toán");
        add(labelThanhtoan);
        labelThanhtoan.setBounds(20, 220, 160, 18);

        textManv.setToolTipText("");
        add(textManv);
        textManv.setBounds(140, 100, 150, 24);

        labelNgaylap.setText("Ngày Lập");
        add(labelNgaylap);
        labelNgaylap.setBounds(20, 130, 120, 18);

        textNgaylap.setToolTipText("");
        textNgaylap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textNgaylapActionPerformed(evt);
            }
        });
        add(textNgaylap);
        textNgaylap.setBounds(140, 130, 150, 24);

        jLabelTthd.setText("THÔNG TIN HÓA ĐƠN");
        add(jLabelTthd);
        jLabelTthd.setBounds(110, 10, 160, 18);

        textMahd1.setToolTipText("");
        add(textMahd1);
        textMahd1.setBounds(740, 40, 150, 24);

        textMakh1.setToolTipText("");
        add(textMakh1);
        textMakh1.setBounds(740, 70, 150, 24);

        textThanhtien1.setToolTipText("");
        textThanhtien1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textThanhtien1ActionPerformed(evt);
            }
        });
        add(textThanhtien1);
        textThanhtien1.setBounds(740, 190, 150, 24);

        labelMahd1.setText("Mã Hóa Đơn");
        add(labelMahd1);
        labelMahd1.setBounds(610, 40, 88, 18);

        labelManv1.setText("Số Lượng");
        add(labelManv1);
        labelManv1.setBounds(610, 100, 88, 18);

        labelMakh1.setText("Mã Sản Phẩm");
        add(labelMakh1);
        labelMakh1.setBounds(610, 70, 150, 18);

        labelThanhtien1.setText("Thành Tiền");
        add(labelThanhtien1);
        labelThanhtien1.setBounds(610, 190, 88, 18);

        textManv1.setToolTipText("");
        add(textManv1);
        textManv1.setBounds(740, 100, 150, 24);

        labelNgaylap1.setText("Đơn Giá");
        add(labelNgaylap1);
        labelNgaylap1.setBounds(610, 130, 88, 18);

        textNgaylap1.setToolTipText("");
        textNgaylap1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textNgaylap1ActionPerformed(evt);
            }
        });
        add(textNgaylap1);
        textNgaylap1.setBounds(740, 130, 150, 24);

        labelTongtien.setText("Tổng Tiền");
        add(labelTongtien);
        labelTongtien.setBounds(20, 160, 88, 18);

        textTongtien.setToolTipText("");
        textTongtien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textTongtienActionPerformed(evt);
            }
        });
        add(textTongtien);
        textTongtien.setBounds(140, 160, 150, 24);

        textTienkm.setToolTipText("");
        textTienkm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textTienkmActionPerformed(evt);
            }
        });
        add(textTienkm);
        textTienkm.setBounds(140, 190, 150, 24);

        labelTienkm.setText("Tiền Khuyến Mãi");
        add(labelTienkm);
        labelTienkm.setBounds(20, 190, 160, 18);

        labelTienkm1.setText("Tiền Khuyến Mãi");
        add(labelTienkm1);
        labelTienkm1.setBounds(610, 160, 180, 18);

        textTienkm1.setToolTipText("");
        textTienkm1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textTienkm1ActionPerformed(evt);
            }
        });
        add(textTienkm1);
        textTienkm1.setBounds(740, 160, 150, 24);

        bntThem.setText("Thêm");
        bntThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntThemActionPerformed(evt);
            }
        });
        add(bntThem);
        bntThem.setBounds(300, 40, 80, 24);

        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });
        add(btnSua);
        btnSua.setBounds(300, 85, 80, 24);

        bntXoa.setText("Xóa");
        bntXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntXoaActionPerformed(evt);
            }
        });
        add(bntXoa);
        bntXoa.setBounds(300, 130, 80, 24);

        btnTim.setText("Tìm");
        btnTim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimActionPerformed(evt);
            }
        });
        add(btnTim);
        btnTim.setBounds(300, 175, 80, 24);

        btnTailai.setText("Tải Lại");
        btnTailai.setActionCommand("Refresh");
        btnTailai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTailaiActionPerformed(evt);
            }
        });
        add(btnTailai);
        btnTailai.setBounds(300, 220, 80, 24);

        jLabelCthd.setText("CHI TIẾT HÓA ĐƠN");
        add(jLabelCthd);
        jLabelCthd.setBounds(760, 10, 160, 18);

        bntThem1.setText("Thêm");
        bntThem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntThem1ActionPerformed(evt);
            }
        });
        add(bntThem1);
        bntThem1.setBounds(900, 40, 80, 24);

        btnSua1.setText("Sửa");
        btnSua1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSua1ActionPerformed(evt);
            }
        });
        add(btnSua1);
        btnSua1.setBounds(900, 78, 80, 24);

        bntXoa1.setText("Xóa");
        bntXoa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntXoa1ActionPerformed(evt);
            }
        });
        add(bntXoa1);
        bntXoa1.setBounds(900, 116, 80, 24);

        btnTim1.setText("Tìm");
        btnTim1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTim1ActionPerformed(evt);
            }
        });
        add(btnTim1);
        btnTim1.setBounds(900, 154, 80, 24);

        btnTailai1.setText("Tải Lại");
        btnTailai1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTailai1ActionPerformed(evt);
            }
        });
        add(btnTailai1);
        btnTailai1.setBounds(900, 190, 80, 24);

        jTableTthd.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã Hóa Đơn", "Mã Khách Hàng", "Mã Nhân Viên", "Ngày Lập", "Tổng Tiền", "Tiền Khuyến Mãi", "Tiền Thanh Toán"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableTthd.setAutoscrolls(false);
        jTableTthd.setColumnSelectionAllowed(true);
        jTableTthd.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTableTthd);

        add(jScrollPane1);
        jScrollPane1.setBounds(10, 280, 980, 300);

        jTableCthd.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Mã Hóa Đơn", "Mã Sản Phẩm", "Số Lượng", "Đơn Giá", "Tiền Khuyến Mãi", "Thành Tiền"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableCthd.setColumnSelectionAllowed(true);
        jTableCthd.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(jTableCthd);

        add(jScrollPane2);
        jScrollPane2.setBounds(10, 590, 980, 220);
    }// </editor-fold>//GEN-END:initComponents

    private void textTienthanhtoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textTienthanhtoanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textTienthanhtoanActionPerformed

    private void textNgaylapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNgaylapActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textNgaylapActionPerformed

    private void textThanhtien1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textThanhtien1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textThanhtien1ActionPerformed

    private void textNgaylap1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNgaylap1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textNgaylap1ActionPerformed

    private void textTongtienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textTongtienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textTongtienActionPerformed

    private void textTienkmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textTienkmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textTienkmActionPerformed

    private void textTienkm1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textTienkm1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textTienkm1ActionPerformed

    private void bntThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntThemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bntThemActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSuaActionPerformed

    private void bntXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntXoaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bntXoaActionPerformed

    private void btnTimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTimActionPerformed

    private void btnTailaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTailaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTailaiActionPerformed

    private void bntThem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntThem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bntThem1ActionPerformed

    private void btnSua1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSua1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSua1ActionPerformed

    private void bntXoa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntXoa1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bntXoa1ActionPerformed

    private void btnTim1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTim1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTim1ActionPerformed

    private void btnTailai1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTailai1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTailai1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntThem;
    private javax.swing.JButton bntThem1;
    private javax.swing.JButton bntXoa;
    private javax.swing.JButton bntXoa1;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnSua1;
    private javax.swing.JButton btnTailai;
    private javax.swing.JButton btnTailai1;
    private javax.swing.JButton btnTim;
    private javax.swing.JButton btnTim1;
    private javax.swing.JLabel jLabelCthd;
    private javax.swing.JLabel jLabelTthd;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableCthd;
    private javax.swing.JTable jTableTthd;
    private javax.swing.JTextField textMahd;
    private javax.swing.JTextField textMahd1;
    private javax.swing.JTextField textMakh;
    private javax.swing.JTextField textMakh1;
    private javax.swing.JTextField textManv;
    private javax.swing.JTextField textManv1;
    private javax.swing.JTextField textNgaylap;
    private javax.swing.JTextField textNgaylap1;
    private javax.swing.JTextField textThanhtien1;
    private javax.swing.JTextField textTienkm;
    private javax.swing.JTextField textTienkm1;
    private javax.swing.JTextField textTienthanhtoan;
    private javax.swing.JTextField textTongtien;
    // End of variables declaration//GEN-END:variables
}
