/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.mavenproject1;

/**
 *
 * @author ASUS
 */
public class FormKhuyenMai extends javax.swing.JPanel {

    /**
     * Creates new form FormKhuyenMai
     */
    public FormKhuyenMai() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JPanel tablePanel = new javax.swing.JPanel();
        javax.swing.JLabel lbTableTitle = new javax.swing.JLabel();
        javax.swing.JButton btnTimKiem = new javax.swing.JButton();
        javax.swing.JButton btnReset = new javax.swing.JButton();
        javax.swing.JPanel pluginPanel = new javax.swing.JPanel();
        javax.swing.JPanel ctKMPanel = new javax.swing.JPanel();
        javax.swing.JLabel lbKhuyenMaiUnit = new javax.swing.JLabel();
        javax.swing.JLabel lbCTKMTitle = new javax.swing.JLabel();
        javax.swing.JTextField txtMaTK1 = new javax.swing.JTextField();
        javax.swing.JLabel lbMaKM = new javax.swing.JLabel();
        javax.swing.JTextField txtSanPham = new javax.swing.JTextField();
        javax.swing.JLabel lbSanPham = new javax.swing.JLabel();
        javax.swing.JTextField txtMaSP = new javax.swing.JTextField();
        javax.swing.JLabel lbMaSP = new javax.swing.JLabel();
        javax.swing.JTextField txtKhuyenMai = new javax.swing.JTextField();
        javax.swing.JLabel lbKhuyenMai = new javax.swing.JLabel();
        javax.swing.JButton btnSelectSP = new javax.swing.JButton();
        javax.swing.JButton btnThemCT = new javax.swing.JButton();
        javax.swing.JButton btnSuaCT = new javax.swing.JButton();
        javax.swing.JButton btnXoaCT = new javax.swing.JButton();
        javax.swing.JPanel infoPanel = new javax.swing.JPanel();
        javax.swing.JLabel lbDetailTitle = new javax.swing.JLabel();
        javax.swing.JLabel lbMakM = new javax.swing.JLabel();
        javax.swing.JLabel lbTieuDe = new javax.swing.JLabel();
        javax.swing.JTextField txtMaKM = new javax.swing.JTextField();
        javax.swing.JTextField txtTieuDe = new javax.swing.JTextField();
        javax.swing.JButton btnThem = new javax.swing.JButton();
        javax.swing.JButton btnSua = new javax.swing.JButton();
        javax.swing.JButton btnXoa = new javax.swing.JButton();
        javax.swing.JLabel lbNoiDung = new javax.swing.JLabel();
        javax.swing.JLabel lbNgayBD = new javax.swing.JLabel();
        javax.swing.JTextField txtNgayBD = new javax.swing.JTextField();
        javax.swing.JTextField txtNgayKT = new javax.swing.JTextField();
        javax.swing.JLabel lbNgayLap = new javax.swing.JLabel();
        javax.swing.JScrollPane jScrollPane1 = new javax.swing.JScrollPane();
        javax.swing.JTextArea taNoiDung = new javax.swing.JTextArea();
        javax.swing.JPanel detailTablePanel = new javax.swing.JPanel();
        javax.swing.JButton btnReset1 = new javax.swing.JButton();

        setLayout(null);

        tablePanel.setBackground(new java.awt.Color(255, 255, 255));
        tablePanel.setLayout(null);

        lbTableTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbTableTitle.setForeground(new java.awt.Color(37, 57, 111));
        lbTableTitle.setText("Danh sách");
        tablePanel.add(lbTableTitle);
        lbTableTitle.setBounds(30, 10, 240, 40);

        btnTimKiem.setBackground(new java.awt.Color(229, 239, 255));
        btnTimKiem.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnTimKiem.setForeground(new java.awt.Color(54, 123, 245));
        btnTimKiem.setText("Tìm kiếm");
        btnTimKiem.setBorderPainted(false);
        btnTimKiem.setFocusPainted(false);
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });
        tablePanel.add(btnTimKiem);
        btnTimKiem.setBounds(410, 20, 170, 35);

        btnReset.setText("jButton3");
        tablePanel.add(btnReset);
        btnReset.setBounds(590, 20, 40, 35);

        add(tablePanel);
        tablePanel.setBounds(10, 400, 650, 410);

        pluginPanel.setBackground(new java.awt.Color(255, 255, 255));
        pluginPanel.setLayout(null);

        ctKMPanel.setBackground(new java.awt.Color(255, 255, 255));
        ctKMPanel.setLayout(null);

        lbKhuyenMaiUnit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbKhuyenMaiUnit.setText("đồng");
        ctKMPanel.add(lbKhuyenMaiUnit);
        lbKhuyenMaiUnit.setBounds(390, 100, 50, 40);

        lbCTKMTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbCTKMTitle.setForeground(new java.awt.Color(37, 57, 111));
        lbCTKMTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbCTKMTitle.setText("Chi tiết khuyến mãi");
        ctKMPanel.add(lbCTKMTitle);
        lbCTKMTitle.setBounds(110, 20, 270, 40);

        txtMaTK1.setBackground(new java.awt.Color(245, 245, 245));
        txtMaTK1.setEnabled(false);
        ctKMPanel.add(txtMaTK1);
        txtMaTK1.setBounds(30, 100, 70, 35);

        lbMaKM.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbMaKM.setText("Mã KM");
        ctKMPanel.add(lbMaKM);
        lbMaKM.setBounds(31, 80, 70, 20);

        txtSanPham.setBackground(new java.awt.Color(245, 245, 245));
        txtSanPham.setEnabled(false);
        ctKMPanel.add(txtSanPham);
        txtSanPham.setBounds(155, 160, 285, 35);

        lbSanPham.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbSanPham.setText("Sản phẩm");
        ctKMPanel.add(lbSanPham);
        lbSanPham.setBounds(156, 140, 120, 20);

        txtMaSP.setBackground(new java.awt.Color(245, 245, 245));
        txtMaSP.setEnabled(false);
        ctKMPanel.add(txtMaSP);
        txtMaSP.setBounds(30, 160, 70, 35);

        lbMaSP.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbMaSP.setText("Mã SP");
        ctKMPanel.add(lbMaSP);
        lbMaSP.setBounds(31, 140, 70, 20);

        txtKhuyenMai.setBackground(new java.awt.Color(245, 245, 245));
        txtKhuyenMai.setEnabled(false);
        ctKMPanel.add(txtKhuyenMai);
        txtKhuyenMai.setBounds(110, 100, 330, 35);

        lbKhuyenMai.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbKhuyenMai.setText("Khuyến mãi");
        ctKMPanel.add(lbKhuyenMai);
        lbKhuyenMai.setBounds(111, 80, 120, 20);

        btnSelectSP.setText("jButton1");
        ctKMPanel.add(btnSelectSP);
        btnSelectSP.setBounds(110, 160, 35, 35);

        btnThemCT.setBackground(new java.awt.Color(220, 247, 227));
        btnThemCT.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnThemCT.setForeground(new java.awt.Color(47, 168, 79));
        btnThemCT.setText("Thêm");
        btnThemCT.setBorderPainted(false);
        btnThemCT.setFocusPainted(false);
        btnThemCT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemCTActionPerformed(evt);
            }
        });
        ctKMPanel.add(btnThemCT);
        btnThemCT.setBounds(30, 275, 410, 40);

        btnSuaCT.setBackground(new java.awt.Color(252, 243, 215));
        btnSuaCT.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnSuaCT.setForeground(new java.awt.Color(243, 170, 24));
        btnSuaCT.setText("Sửa");
        btnSuaCT.setBorderPainted(false);
        btnSuaCT.setFocusPainted(false);
        ctKMPanel.add(btnSuaCT);
        btnSuaCT.setBounds(30, 330, 200, 40);

        btnXoaCT.setBackground(new java.awt.Color(254, 228, 226));
        btnXoaCT.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnXoaCT.setForeground(new java.awt.Color(234, 61, 47));
        btnXoaCT.setText("Xóa");
        btnXoaCT.setBorderPainted(false);
        btnXoaCT.setFocusPainted(false);
        ctKMPanel.add(btnXoaCT);
        btnXoaCT.setBounds(240, 330, 200, 40);

        pluginPanel.add(ctKMPanel);
        ctKMPanel.setBounds(0, 0, 470, 380);

        add(pluginPanel);
        pluginPanel.setBounds(520, 10, 470, 380);

        infoPanel.setBackground(new java.awt.Color(255, 255, 255));
        infoPanel.setLayout(null);

        lbDetailTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbDetailTitle.setForeground(new java.awt.Color(37, 57, 111));
        lbDetailTitle.setText("Thông tin khuyến mãi");
        infoPanel.add(lbDetailTitle);
        lbDetailTitle.setBounds(130, 20, 290, 40);

        lbMakM.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbMakM.setText("Mã");
        infoPanel.add(lbMakM);
        lbMakM.setBounds(31, 80, 70, 20);

        lbTieuDe.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbTieuDe.setText("Tiêu đề");
        infoPanel.add(lbTieuDe);
        lbTieuDe.setBounds(121, 80, 120, 20);

        txtMaKM.setBackground(new java.awt.Color(245, 245, 245));
        txtMaKM.setEnabled(false);
        infoPanel.add(txtMaKM);
        txtMaKM.setBounds(30, 100, 70, 35);
        infoPanel.add(txtTieuDe);
        txtTieuDe.setBounds(120, 100, 350, 35);

        btnThem.setBackground(new java.awt.Color(220, 247, 227));
        btnThem.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnThem.setForeground(new java.awt.Color(47, 168, 79));
        btnThem.setText("Thêm");
        btnThem.setBorderPainted(false);
        btnThem.setFocusPainted(false);
        infoPanel.add(btnThem);
        btnThem.setBounds(310, 275, 160, 40);

        btnSua.setBackground(new java.awt.Color(252, 243, 215));
        btnSua.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnSua.setForeground(new java.awt.Color(243, 170, 24));
        btnSua.setText("Sửa");
        btnSua.setBorderPainted(false);
        btnSua.setFocusPainted(false);
        infoPanel.add(btnSua);
        btnSua.setBounds(310, 220, 160, 40);

        btnXoa.setBackground(new java.awt.Color(254, 228, 226));
        btnXoa.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnXoa.setForeground(new java.awt.Color(234, 61, 47));
        btnXoa.setText("Xóa");
        btnXoa.setBorderPainted(false);
        btnXoa.setFocusPainted(false);
        infoPanel.add(btnXoa);
        btnXoa.setBounds(310, 330, 160, 40);

        lbNoiDung.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbNoiDung.setText("Nội dung");
        infoPanel.add(lbNoiDung);
        lbNoiDung.setBounds(31, 200, 130, 20);

        lbNgayBD.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbNgayBD.setText("Ngày BD");
        infoPanel.add(lbNgayBD);
        lbNgayBD.setBounds(31, 140, 120, 20);
        infoPanel.add(txtNgayBD);
        txtNgayBD.setBounds(30, 160, 210, 35);
        infoPanel.add(txtNgayKT);
        txtNgayKT.setBounds(260, 160, 210, 35);

        lbNgayLap.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbNgayLap.setText("Ngày KT");
        infoPanel.add(lbNgayLap);
        lbNgayLap.setBounds(261, 140, 150, 20);

        taNoiDung.setColumns(20);
        taNoiDung.setRows(5);
        jScrollPane1.setViewportView(taNoiDung);

        infoPanel.add(jScrollPane1);
        jScrollPane1.setBounds(30, 220, 260, 150);

        add(infoPanel);
        infoPanel.setBounds(10, 10, 500, 380);

        detailTablePanel.setBackground(new java.awt.Color(255, 255, 255));
        detailTablePanel.setLayout(null);

        btnReset1.setText("jButton3");
        detailTablePanel.add(btnReset1);
        btnReset1.setBounds(250, 20, 40, 35);

        add(detailTablePanel);
        detailTablePanel.setBounds(670, 400, 320, 410);
    }// </editor-fold>//GEN-END:initComponents

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTimKiemActionPerformed

    private void btnThemCTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemCTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnThemCTActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
