/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.mavenproject1;

/**
 *
 * @author ASUS
 */
public class FormSanPham extends javax.swing.JPanel {

    /**
     * Creates new form FormSanPham
     */
    public FormSanPham() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JPanel tablePanel = new javax.swing.JPanel();
        javax.swing.JLabel lbTableTitle = new javax.swing.JLabel();
        javax.swing.JButton btnTimKiem = new javax.swing.JButton();
        javax.swing.JButton btnReset = new javax.swing.JButton();
        javax.swing.JPanel pluginPanel = new javax.swing.JPanel();
        javax.swing.JPanel CategoryPanel = new javax.swing.JPanel();
        javax.swing.JLabel lbCategoryTitle = new javax.swing.JLabel();
        javax.swing.JTextField txtMaLoaiSP = new javax.swing.JTextField();
        javax.swing.JLabel lbMaLoaiSP = new javax.swing.JLabel();
        javax.swing.JLabel lbMota = new javax.swing.JLabel();
        javax.swing.JTextField txtTenLoaiSP = new javax.swing.JTextField();
        javax.swing.JLabel lbTenLoaiSP = new javax.swing.JLabel();
        javax.swing.JButton btnThemLoaiSP = new javax.swing.JButton();
        javax.swing.JButton btnSuaLoaiSP = new javax.swing.JButton();
        javax.swing.JButton btnXoaLoaiSP = new javax.swing.JButton();
        javax.swing.JScrollPane jScrollPane2 = new javax.swing.JScrollPane();
        javax.swing.JTextArea taMota = new javax.swing.JTextArea();
        javax.swing.JPanel detailSPPanel = new javax.swing.JPanel();
        javax.swing.JLabel lbDetailSPTitle = new javax.swing.JLabel();
        javax.swing.JPanel imagePanel = new javax.swing.JPanel();
        javax.swing.JLabel imgSP = new javax.swing.JLabel();
        javax.swing.JScrollPane jScrollPane1 = new javax.swing.JScrollPane();
        javax.swing.JTextArea taMotaSP = new javax.swing.JTextArea();
        javax.swing.JLabel lbMotaSP = new javax.swing.JLabel();
        javax.swing.JButton btnLuu = new javax.swing.JButton();
        javax.swing.JPanel infoPanel = new javax.swing.JPanel();
        javax.swing.JLabel lbDonGiaUnit = new javax.swing.JLabel();
        javax.swing.JLabel lbDetailTitle = new javax.swing.JLabel();
        javax.swing.JLabel lbMaSP = new javax.swing.JLabel();
        javax.swing.JLabel lbLoaiSP = new javax.swing.JLabel();
        javax.swing.JTextField txtMaSP = new javax.swing.JTextField();
        javax.swing.JTextField txtLoaiPS = new javax.swing.JTextField();
        javax.swing.JButton btnThem = new javax.swing.JButton();
        javax.swing.JButton btnSua = new javax.swing.JButton();
        javax.swing.JButton btnXoa = new javax.swing.JButton();
        javax.swing.JTextField txtTenSP = new javax.swing.JTextField();
        javax.swing.JLabel lbTenSP = new javax.swing.JLabel();
        javax.swing.JLabel lbMaNCC = new javax.swing.JLabel();
        javax.swing.JTextField txtMaNCC = new javax.swing.JTextField();
        javax.swing.JTextField txtDonVi = new javax.swing.JTextField();
        javax.swing.JLabel lbDonVi = new javax.swing.JLabel();
        javax.swing.JLabel lbDonGia = new javax.swing.JLabel();
        javax.swing.JTextField txtDonGia = new javax.swing.JTextField();
        javax.swing.JLabel lbSoLuong = new javax.swing.JLabel();
        javax.swing.JTextField txtSoLuong = new javax.swing.JTextField();
        javax.swing.JButton btnSelectKH = new javax.swing.JButton();
        javax.swing.JButton btnSelectKH1 = new javax.swing.JButton();
        javax.swing.JPanel tableLoaiSPPanel = new javax.swing.JPanel();
        javax.swing.JButton btnResetCategory = new javax.swing.JButton();
        javax.swing.JLabel lbCategoryTableTitle = new javax.swing.JLabel();

        setLayout(null);

        tablePanel.setBackground(new java.awt.Color(255, 255, 255));
        tablePanel.setLayout(null);

        lbTableTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbTableTitle.setForeground(new java.awt.Color(37, 57, 111));
        lbTableTitle.setText("Danh sách");
        tablePanel.add(lbTableTitle);
        lbTableTitle.setBounds(30, 10, 240, 40);

        btnTimKiem.setBackground(new java.awt.Color(229, 239, 255));
        btnTimKiem.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnTimKiem.setForeground(new java.awt.Color(54, 123, 245));
        btnTimKiem.setText("Tìm kiếm");
        btnTimKiem.setBorderPainted(false);
        btnTimKiem.setFocusPainted(false);
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });
        tablePanel.add(btnTimKiem);
        btnTimKiem.setBounds(410, 20, 170, 35);

        btnReset.setText("jButton3");
        tablePanel.add(btnReset);
        btnReset.setBounds(590, 20, 40, 35);

        add(tablePanel);
        tablePanel.setBounds(10, 400, 650, 410);

        pluginPanel.setBackground(new java.awt.Color(255, 255, 255));
        pluginPanel.setLayout(null);

        CategoryPanel.setBackground(new java.awt.Color(255, 255, 255));
        CategoryPanel.setLayout(null);

        lbCategoryTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbCategoryTitle.setForeground(new java.awt.Color(37, 57, 111));
        lbCategoryTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbCategoryTitle.setText("Loại sản phẩm");
        CategoryPanel.add(lbCategoryTitle);
        lbCategoryTitle.setBounds(110, 20, 270, 40);

        txtMaLoaiSP.setBackground(new java.awt.Color(245, 245, 245));
        txtMaLoaiSP.setEnabled(false);
        CategoryPanel.add(txtMaLoaiSP);
        txtMaLoaiSP.setBounds(30, 100, 70, 35);

        lbMaLoaiSP.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbMaLoaiSP.setText("Mã");
        CategoryPanel.add(lbMaLoaiSP);
        lbMaLoaiSP.setBounds(31, 80, 70, 20);

        lbMota.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbMota.setText("Mô tả");
        CategoryPanel.add(lbMota);
        lbMota.setBounds(31, 150, 120, 20);

        txtTenLoaiSP.setBackground(new java.awt.Color(255, 255, 255));
        CategoryPanel.add(txtTenLoaiSP);
        txtTenLoaiSP.setBounds(110, 100, 330, 35);

        lbTenLoaiSP.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbTenLoaiSP.setText("Tên");
        CategoryPanel.add(lbTenLoaiSP);
        lbTenLoaiSP.setBounds(111, 80, 130, 20);

        btnThemLoaiSP.setBackground(new java.awt.Color(220, 247, 227));
        btnThemLoaiSP.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnThemLoaiSP.setForeground(new java.awt.Color(47, 168, 79));
        btnThemLoaiSP.setText("Thêm");
        btnThemLoaiSP.setBorderPainted(false);
        btnThemLoaiSP.setFocusPainted(false);
        btnThemLoaiSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemLoaiSPActionPerformed(evt);
            }
        });
        CategoryPanel.add(btnThemLoaiSP);
        btnThemLoaiSP.setBounds(30, 280, 410, 35);

        btnSuaLoaiSP.setBackground(new java.awt.Color(252, 243, 215));
        btnSuaLoaiSP.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnSuaLoaiSP.setForeground(new java.awt.Color(243, 170, 24));
        btnSuaLoaiSP.setText("Sửa");
        btnSuaLoaiSP.setBorderPainted(false);
        btnSuaLoaiSP.setFocusPainted(false);
        CategoryPanel.add(btnSuaLoaiSP);
        btnSuaLoaiSP.setBounds(30, 330, 270, 40);

        btnXoaLoaiSP.setBackground(new java.awt.Color(254, 228, 226));
        btnXoaLoaiSP.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnXoaLoaiSP.setForeground(new java.awt.Color(234, 61, 47));
        btnXoaLoaiSP.setText("Xóa");
        btnXoaLoaiSP.setBorderPainted(false);
        btnXoaLoaiSP.setFocusPainted(false);
        CategoryPanel.add(btnXoaLoaiSP);
        btnXoaLoaiSP.setBounds(310, 330, 130, 40);

        taMota.setColumns(20);
        taMota.setRows(5);
        jScrollPane2.setViewportView(taMota);

        CategoryPanel.add(jScrollPane2);
        jScrollPane2.setBounds(30, 170, 410, 96);

        pluginPanel.add(CategoryPanel);
        CategoryPanel.setBounds(0, 0, 470, 380);

        add(pluginPanel);
        pluginPanel.setBounds(520, 10, 470, 380);

        detailSPPanel.setBackground(new java.awt.Color(255, 255, 255));
        detailSPPanel.setLayout(null);

        lbDetailSPTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbDetailSPTitle.setForeground(new java.awt.Color(37, 57, 111));
        lbDetailSPTitle.setText("Nội dung sản phẩm");
        detailSPPanel.add(lbDetailSPTitle);
        lbDetailSPTitle.setBounds(130, 20, 290, 40);

        imagePanel.setLayout(null);
        imagePanel.add(imgSP);
        imgSP.setBounds(0, 0, 170, 170);

        detailSPPanel.add(imagePanel);
        imagePanel.setBounds(30, 100, 170, 170);

        taMotaSP.setColumns(20);
        taMotaSP.setRows(5);
        jScrollPane1.setViewportView(taMotaSP);

        detailSPPanel.add(jScrollPane1);
        jScrollPane1.setBounds(210, 100, 240, 170);

        lbMotaSP.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbMotaSP.setText("Mô tả");
        detailSPPanel.add(lbMotaSP);
        lbMotaSP.setBounds(211, 80, 70, 20);

        btnLuu.setBackground(new java.awt.Color(252, 243, 215));
        btnLuu.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnLuu.setForeground(new java.awt.Color(243, 170, 24));
        btnLuu.setText("Lưu");
        btnLuu.setBorderPainted(false);
        btnLuu.setFocusPainted(false);
        btnLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuActionPerformed(evt);
            }
        });
        detailSPPanel.add(btnLuu);
        btnLuu.setBounds(30, 280, 420, 40);

        add(detailSPPanel);
        detailSPPanel.setBounds(520, 10, 470, 380);

        infoPanel.setBackground(new java.awt.Color(255, 255, 255));
        infoPanel.setLayout(null);

        lbDonGiaUnit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbDonGiaUnit.setText("đồng");
        infoPanel.add(lbDonGiaUnit);
        lbDonGiaUnit.setBounds(150, 220, 50, 40);

        lbDetailTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbDetailTitle.setForeground(new java.awt.Color(37, 57, 111));
        lbDetailTitle.setText("Thông tin sản phẩm");
        infoPanel.add(lbDetailTitle);
        lbDetailTitle.setBounds(130, 20, 290, 40);

        lbMaSP.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbMaSP.setText("Mã");
        infoPanel.add(lbMaSP);
        lbMaSP.setBounds(31, 80, 70, 20);

        lbLoaiSP.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbLoaiSP.setText("Loại");
        infoPanel.add(lbLoaiSP);
        lbLoaiSP.setBounds(311, 80, 120, 20);

        txtMaSP.setBackground(new java.awt.Color(245, 245, 245));
        txtMaSP.setEnabled(false);
        infoPanel.add(txtMaSP);
        txtMaSP.setBounds(30, 100, 70, 35);

        txtLoaiPS.setBackground(new java.awt.Color(245, 245, 245));
        txtLoaiPS.setEnabled(false);
        infoPanel.add(txtLoaiPS);
        txtLoaiPS.setBounds(310, 100, 120, 35);

        btnThem.setBackground(new java.awt.Color(220, 247, 227));
        btnThem.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnThem.setForeground(new java.awt.Color(47, 168, 79));
        btnThem.setText("Thêm");
        btnThem.setBorderPainted(false);
        btnThem.setFocusPainted(false);
        infoPanel.add(btnThem);
        btnThem.setBounds(310, 280, 160, 40);

        btnSua.setBackground(new java.awt.Color(252, 243, 215));
        btnSua.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnSua.setForeground(new java.awt.Color(243, 170, 24));
        btnSua.setText("Sửa");
        btnSua.setBorderPainted(false);
        btnSua.setFocusPainted(false);
        infoPanel.add(btnSua);
        btnSua.setBounds(30, 280, 260, 40);

        btnXoa.setBackground(new java.awt.Color(254, 228, 226));
        btnXoa.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnXoa.setForeground(new java.awt.Color(234, 61, 47));
        btnXoa.setText("Xóa");
        btnXoa.setBorderPainted(false);
        btnXoa.setFocusPainted(false);
        infoPanel.add(btnXoa);
        btnXoa.setBounds(310, 330, 160, 40);
        infoPanel.add(txtTenSP);
        txtTenSP.setBounds(30, 160, 260, 35);

        lbTenSP.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbTenSP.setText("Tên");
        infoPanel.add(lbTenSP);
        lbTenSP.setBounds(31, 140, 80, 20);

        lbMaNCC.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbMaNCC.setText("Nhà cung cấp");
        infoPanel.add(lbMaNCC);
        lbMaNCC.setBounds(311, 140, 120, 20);

        txtMaNCC.setBackground(new java.awt.Color(245, 245, 245));
        txtMaNCC.setEnabled(false);
        txtMaNCC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaNCCActionPerformed(evt);
            }
        });
        infoPanel.add(txtMaNCC);
        txtMaNCC.setBounds(310, 160, 120, 35);

        txtDonVi.setBackground(new java.awt.Color(255, 255, 255));
        infoPanel.add(txtDonVi);
        txtDonVi.setBounds(220, 220, 70, 35);

        lbDonVi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbDonVi.setText("Đơn vị");
        infoPanel.add(lbDonVi);
        lbDonVi.setBounds(221, 200, 60, 20);

        lbDonGia.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbDonGia.setText("Đơn giá");
        infoPanel.add(lbDonGia);
        lbDonGia.setBounds(31, 200, 130, 20);
        infoPanel.add(txtDonGia);
        txtDonGia.setBounds(30, 220, 170, 35);

        lbSoLuong.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbSoLuong.setText("Số lượng");
        infoPanel.add(lbSoLuong);
        lbSoLuong.setBounds(311, 200, 90, 20);

        txtSoLuong.setBackground(new java.awt.Color(245, 245, 245));
        txtSoLuong.setEnabled(false);
        infoPanel.add(txtSoLuong);
        txtSoLuong.setBounds(310, 220, 120, 35);

        btnSelectKH.setText("jButton1");
        infoPanel.add(btnSelectKH);
        btnSelectKH.setBounds(440, 100, 35, 35);

        btnSelectKH1.setText("jButton1");
        infoPanel.add(btnSelectKH1);
        btnSelectKH1.setBounds(440, 160, 35, 35);

        add(infoPanel);
        infoPanel.setBounds(10, 10, 500, 380);

        tableLoaiSPPanel.setBackground(new java.awt.Color(255, 255, 255));
        tableLoaiSPPanel.setLayout(null);

        btnResetCategory.setText("jButton3");
        tableLoaiSPPanel.add(btnResetCategory);
        btnResetCategory.setBounds(250, 20, 40, 35);

        lbCategoryTableTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbCategoryTableTitle.setForeground(new java.awt.Color(37, 57, 111));
        lbCategoryTableTitle.setText("Loại");
        tableLoaiSPPanel.add(lbCategoryTableTitle);
        lbCategoryTableTitle.setBounds(30, 10, 130, 40);

        add(tableLoaiSPPanel);
        tableLoaiSPPanel.setBounds(670, 400, 320, 410);
    }// </editor-fold>//GEN-END:initComponents

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTimKiemActionPerformed

    private void btnThemLoaiSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemLoaiSPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnThemLoaiSPActionPerformed

    private void txtMaNCCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaNCCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaNCCActionPerformed

    private void btnLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLuuActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
