/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.mavenproject1;

/**
 *
 * @author ASUS
 */
public class FormPhieuNhap extends javax.swing.JPanel {

    /**
     * Creates new form FormPhieuNhap
     */
    public FormPhieuNhap() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JPanel tablePanel2 = new javax.swing.JPanel();
        javax.swing.JLabel lbTableTitle2 = new javax.swing.JLabel();
        javax.swing.JButton btnTimKiem2 = new javax.swing.JButton();
        javax.swing.JButton btnReset = new javax.swing.JButton();
        javax.swing.JPanel pluginPanel = new javax.swing.JPanel();
        javax.swing.JPanel detailPanel = new javax.swing.JPanel();
        javax.swing.JLabel lbThanhTienCTUnit = new javax.swing.JLabel();
        javax.swing.JLabel lbPasswordTitle = new javax.swing.JLabel();
        javax.swing.JTextField txtMaPNCT = new javax.swing.JTextField();
        javax.swing.JLabel lbMaPNCT = new javax.swing.JLabel();
        javax.swing.JTextField txtSanPham = new javax.swing.JTextField();
        javax.swing.JLabel lbSanPham = new javax.swing.JLabel();
        javax.swing.JTextField txtSoLuong = new javax.swing.JTextField();
        javax.swing.JLabel lbSoLuong = new javax.swing.JLabel();
        javax.swing.JTextField txtMaSP = new javax.swing.JTextField();
        javax.swing.JLabel lbMaSP = new javax.swing.JLabel();
        javax.swing.JTextField txtThanhTienCT = new javax.swing.JTextField();
        javax.swing.JLabel lbThanhTienCT = new javax.swing.JLabel();
        javax.swing.JLabel lbDonGia = new javax.swing.JLabel();
        javax.swing.JTextField txtDonGia = new javax.swing.JTextField();
        javax.swing.JButton btnSelectSP = new javax.swing.JButton();
        javax.swing.JButton btnThemCT = new javax.swing.JButton();
        javax.swing.JButton btnSuaCT = new javax.swing.JButton();
        javax.swing.JButton btnXoaCT = new javax.swing.JButton();
        javax.swing.JPanel infoPanel = new javax.swing.JPanel();
        javax.swing.JLabel lbTongTienUnit = new javax.swing.JLabel();
        javax.swing.JLabel lbDetailTitle = new javax.swing.JLabel();
        javax.swing.JLabel lbMaPN = new javax.swing.JLabel();
        javax.swing.JLabel lbMaNCC = new javax.swing.JLabel();
        javax.swing.JTextField txtMaHD = new javax.swing.JTextField();
        javax.swing.JTextField txtMaNCC = new javax.swing.JTextField();
        javax.swing.JButton btnThem = new javax.swing.JButton();
        javax.swing.JButton btnSua = new javax.swing.JButton();
        javax.swing.JButton btnXoa = new javax.swing.JButton();
        javax.swing.JTextField txtTotal = new javax.swing.JTextField();
        javax.swing.JLabel lbTotal = new javax.swing.JLabel();
        javax.swing.JLabel lbMaNV = new javax.swing.JLabel();
        javax.swing.JTextField txtMaNV = new javax.swing.JTextField();
        javax.swing.JTextField txtNgayLap = new javax.swing.JTextField();
        javax.swing.JLabel lbNgayLap = new javax.swing.JLabel();
        javax.swing.JButton btnSelectNCC = new javax.swing.JButton();
        javax.swing.JPanel detailTablePanel = new javax.swing.JPanel();
        javax.swing.JButton btnReset1 = new javax.swing.JButton();

        setLayout(null);

        tablePanel2.setBackground(new java.awt.Color(255, 255, 255));
        tablePanel2.setLayout(null);

        lbTableTitle2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbTableTitle2.setForeground(new java.awt.Color(37, 57, 111));
        lbTableTitle2.setText("Danh sách");
        tablePanel2.add(lbTableTitle2);
        lbTableTitle2.setBounds(30, 10, 240, 40);

        btnTimKiem2.setBackground(new java.awt.Color(229, 239, 255));
        btnTimKiem2.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnTimKiem2.setForeground(new java.awt.Color(54, 123, 245));
        btnTimKiem2.setText("Tìm kiếm");
        btnTimKiem2.setBorderPainted(false);
        btnTimKiem2.setFocusPainted(false);
        btnTimKiem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiem2ActionPerformed(evt);
            }
        });
        tablePanel2.add(btnTimKiem2);
        btnTimKiem2.setBounds(410, 20, 170, 35);

        btnReset.setText("jButton3");
        tablePanel2.add(btnReset);
        btnReset.setBounds(590, 20, 40, 35);

        add(tablePanel2);
        tablePanel2.setBounds(10, 400, 650, 410);

        pluginPanel.setBackground(new java.awt.Color(255, 255, 255));
        pluginPanel.setLayout(null);

        detailPanel.setBackground(new java.awt.Color(255, 255, 255));
        detailPanel.setLayout(null);

        lbThanhTienCTUnit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbThanhTienCTUnit.setText("đồng");
        detailPanel.add(lbThanhTienCTUnit);
        lbThanhTienCTUnit.setBounds(390, 100, 50, 40);

        lbPasswordTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbPasswordTitle.setForeground(new java.awt.Color(37, 57, 111));
        lbPasswordTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbPasswordTitle.setText("Chi tiết phiếu nhập");
        detailPanel.add(lbPasswordTitle);
        lbPasswordTitle.setBounds(110, 20, 270, 40);

        txtMaPNCT.setBackground(new java.awt.Color(245, 245, 245));
        txtMaPNCT.setEnabled(false);
        detailPanel.add(txtMaPNCT);
        txtMaPNCT.setBounds(30, 100, 70, 35);

        lbMaPNCT.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbMaPNCT.setText("Mã PN");
        detailPanel.add(lbMaPNCT);
        lbMaPNCT.setBounds(30, 80, 70, 20);

        txtSanPham.setBackground(new java.awt.Color(245, 245, 245));
        txtSanPham.setEnabled(false);
        detailPanel.add(txtSanPham);
        txtSanPham.setBounds(160, 160, 280, 35);

        lbSanPham.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbSanPham.setText("Sản phẩm");
        detailPanel.add(lbSanPham);
        lbSanPham.setBounds(160, 140, 120, 20);

        txtSoLuong.setBackground(new java.awt.Color(255, 255, 255));
        txtSoLuong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSoLuongActionPerformed(evt);
            }
        });
        detailPanel.add(txtSoLuong);
        txtSoLuong.setBounds(160, 220, 80, 35);

        lbSoLuong.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbSoLuong.setText("Số lượng");
        detailPanel.add(lbSoLuong);
        lbSoLuong.setBounds(160, 200, 80, 20);

        txtMaSP.setBackground(new java.awt.Color(245, 245, 245));
        txtMaSP.setEnabled(false);
        detailPanel.add(txtMaSP);
        txtMaSP.setBounds(30, 160, 70, 35);

        lbMaSP.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbMaSP.setText("Mã SP");
        detailPanel.add(lbMaSP);
        lbMaSP.setBounds(30, 140, 70, 20);

        txtThanhTienCT.setBackground(new java.awt.Color(245, 245, 245));
        txtThanhTienCT.setEnabled(false);
        detailPanel.add(txtThanhTienCT);
        txtThanhTienCT.setBounds(160, 100, 280, 35);

        lbThanhTienCT.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbThanhTienCT.setText("Thành tiền");
        detailPanel.add(lbThanhTienCT);
        lbThanhTienCT.setBounds(160, 80, 130, 20);

        lbDonGia.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbDonGia.setText("Đơn giá");
        detailPanel.add(lbDonGia);
        lbDonGia.setBounds(260, 200, 100, 20);

        txtDonGia.setBackground(new java.awt.Color(245, 245, 245));
        txtDonGia.setEnabled(false);
        detailPanel.add(txtDonGia);
        txtDonGia.setBounds(260, 220, 180, 35);

        btnSelectSP.setText("jButton1");
        detailPanel.add(btnSelectSP);
        btnSelectSP.setBounds(110, 160, 40, 35);

        btnThemCT.setBackground(new java.awt.Color(220, 247, 227));
        btnThemCT.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnThemCT.setForeground(new java.awt.Color(47, 168, 79));
        btnThemCT.setText("Thêm");
        btnThemCT.setBorderPainted(false);
        btnThemCT.setFocusPainted(false);
        btnThemCT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemCTActionPerformed(evt);
            }
        });
        detailPanel.add(btnThemCT);
        btnThemCT.setBounds(160, 280, 280, 40);

        btnSuaCT.setBackground(new java.awt.Color(252, 243, 215));
        btnSuaCT.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnSuaCT.setForeground(new java.awt.Color(243, 170, 24));
        btnSuaCT.setText("Sửa");
        btnSuaCT.setBorderPainted(false);
        btnSuaCT.setFocusPainted(false);
        detailPanel.add(btnSuaCT);
        btnSuaCT.setBounds(260, 330, 180, 40);

        btnXoaCT.setBackground(new java.awt.Color(254, 228, 226));
        btnXoaCT.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnXoaCT.setForeground(new java.awt.Color(234, 61, 47));
        btnXoaCT.setText("Xóa");
        btnXoaCT.setBorderPainted(false);
        btnXoaCT.setFocusPainted(false);
        detailPanel.add(btnXoaCT);
        btnXoaCT.setBounds(160, 330, 80, 40);

        pluginPanel.add(detailPanel);
        detailPanel.setBounds(0, 0, 470, 380);

        add(pluginPanel);
        pluginPanel.setBounds(520, 10, 470, 380);

        infoPanel.setBackground(new java.awt.Color(255, 255, 255));
        infoPanel.setLayout(null);

        lbTongTienUnit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTongTienUnit.setText("đồng");
        infoPanel.add(lbTongTienUnit);
        lbTongTienUnit.setBounds(380, 100, 50, 40);

        lbDetailTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbDetailTitle.setForeground(new java.awt.Color(37, 57, 111));
        lbDetailTitle.setText("Thông tin phiếu nhập");
        infoPanel.add(lbDetailTitle);
        lbDetailTitle.setBounds(130, 20, 290, 40);

        lbMaPN.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbMaPN.setText("Mã");
        infoPanel.add(lbMaPN);
        lbMaPN.setBounds(80, 80, 70, 20);

        lbMaNCC.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbMaNCC.setText("Nhà cung cấp");
        infoPanel.add(lbMaNCC);
        lbMaNCC.setBounds(80, 140, 120, 20);

        txtMaHD.setBackground(new java.awt.Color(245, 245, 245));
        txtMaHD.setEnabled(false);
        infoPanel.add(txtMaHD);
        txtMaHD.setBounds(80, 100, 70, 35);

        txtMaNCC.setBackground(new java.awt.Color(245, 245, 245));
        txtMaNCC.setEnabled(false);
        infoPanel.add(txtMaNCC);
        txtMaNCC.setBounds(80, 160, 290, 35);

        btnThem.setBackground(new java.awt.Color(220, 247, 227));
        btnThem.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnThem.setForeground(new java.awt.Color(47, 168, 79));
        btnThem.setText("Thêm");
        btnThem.setBorderPainted(false);
        btnThem.setFocusPainted(false);
        infoPanel.add(btnThem);
        btnThem.setBounds(80, 280, 350, 40);

        btnSua.setBackground(new java.awt.Color(252, 243, 215));
        btnSua.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnSua.setForeground(new java.awt.Color(243, 170, 24));
        btnSua.setText("Sửa");
        btnSua.setBorderPainted(false);
        btnSua.setFocusPainted(false);
        infoPanel.add(btnSua);
        btnSua.setBounds(80, 330, 170, 40);

        btnXoa.setBackground(new java.awt.Color(254, 228, 226));
        btnXoa.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnXoa.setForeground(new java.awt.Color(234, 61, 47));
        btnXoa.setText("Xóa");
        btnXoa.setBorderPainted(false);
        btnXoa.setFocusPainted(false);
        infoPanel.add(btnXoa);
        btnXoa.setBounds(270, 330, 160, 40);

        txtTotal.setBackground(new java.awt.Color(245, 245, 245));
        txtTotal.setEnabled(false);
        infoPanel.add(txtTotal);
        txtTotal.setBounds(170, 100, 260, 35);

        lbTotal.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbTotal.setText("Tổng tiền");
        infoPanel.add(lbTotal);
        lbTotal.setBounds(170, 80, 130, 20);

        lbMaNV.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbMaNV.setText("Nhân viên");
        infoPanel.add(lbMaNV);
        lbMaNV.setBounds(80, 200, 120, 20);

        txtMaNV.setBackground(new java.awt.Color(245, 245, 245));
        txtMaNV.setEnabled(false);
        infoPanel.add(txtMaNV);
        txtMaNV.setBounds(80, 220, 170, 35);

        txtNgayLap.setBackground(new java.awt.Color(245, 245, 245));
        txtNgayLap.setEnabled(false);
        infoPanel.add(txtNgayLap);
        txtNgayLap.setBounds(270, 220, 160, 35);

        lbNgayLap.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbNgayLap.setText("Ngày lập");
        infoPanel.add(lbNgayLap);
        lbNgayLap.setBounds(270, 200, 150, 20);

        btnSelectNCC.setText("jButton1");
        infoPanel.add(btnSelectNCC);
        btnSelectNCC.setBounds(390, 160, 40, 35);

        add(infoPanel);
        infoPanel.setBounds(10, 10, 500, 380);

        detailTablePanel.setBackground(new java.awt.Color(255, 255, 255));
        detailTablePanel.setLayout(null);

        btnReset1.setText("jButton3");
        detailTablePanel.add(btnReset1);
        btnReset1.setBounds(250, 20, 40, 35);

        add(detailTablePanel);
        detailTablePanel.setBounds(670, 400, 320, 410);
    }// </editor-fold>//GEN-END:initComponents

    private void btnTimKiem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiem2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTimKiem2ActionPerformed

    private void txtSoLuongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSoLuongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSoLuongActionPerformed

    private void btnThemCTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemCTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnThemCTActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
