package GUI.Form;/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author PC
 */
public class FormNCC extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
    public FormNCC() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbAddressNCC = new javax.swing.JLabel();
        txtSĐTNCC = new javax.swing.JTextField();
        txtAddressNCC = new javax.swing.JTextField();
        txtNameNCC = new javax.swing.JTextField();
        lbNameNCC = new javax.swing.JLabel();
        lbSĐTNCC = new javax.swing.JLabel();
        lbInfNCC = new javax.swing.JLabel();
        txtMailNCC = new javax.swing.JTextField();
        lbIDNCC = new javax.swing.JLabel();
        txtIDNCC = new javax.swing.JTextField();
        btnAddNCC = new javax.swing.JButton();
        btnFixNCC = new javax.swing.JButton();
        bthDelNCC = new javax.swing.JButton();
        btnReloadNCC = new javax.swing.JButton();
        btnFindNCC = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblListNCC = new javax.swing.JTable();
        lbMailNCC = new javax.swing.JLabel();
        lbListNCC = new javax.swing.JLabel();
        lbMailNCC1 = new javax.swing.JLabel();
        txtMailNCC1 = new javax.swing.JTextField();

        setLayout(null);

        lbAddressNCC.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbAddressNCC.setText("Địa chỉ nhà cung cấp");
        add(lbAddressNCC);
        lbAddressNCC.setBounds(10, 180, 170, 30);

        txtSĐTNCC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSĐTNCCActionPerformed(evt);
            }
        });
        add(txtSĐTNCC);
        txtSĐTNCC.setBounds(200, 130, 220, 30);

        txtAddressNCC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAddressNCCActionPerformed(evt);
            }
        });
        add(txtAddressNCC);
        txtAddressNCC.setBounds(200, 230, 220, 30);

        txtNameNCC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameNCCActionPerformed(evt);
            }
        });
        add(txtNameNCC);
        txtNameNCC.setBounds(200, 80, 220, 30);

        lbNameNCC.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbNameNCC.setText("Tên nhà cung cấp");
        add(lbNameNCC);
        lbNameNCC.setBounds(30, 80, 140, 30);

        lbSĐTNCC.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbSĐTNCC.setText("SĐT nhà cung cấp");
        add(lbSĐTNCC);
        lbSĐTNCC.setBounds(30, 130, 150, 30);

        lbInfNCC.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbInfNCC.setText("Thông tin nhà cung cấp");
        add(lbInfNCC);
        lbInfNCC.setBounds(650, 20, 200, 30);

        txtMailNCC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMailNCCActionPerformed(evt);
            }
        });
        add(txtMailNCC);
        txtMailNCC.setBounds(200, 280, 220, 30);

        lbIDNCC.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbIDNCC.setText("Mã nhà cung cấp");
        add(lbIDNCC);
        lbIDNCC.setBounds(30, 30, 140, 30);

        txtIDNCC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDNCCActionPerformed(evt);
            }
        });
        add(txtIDNCC);
        txtIDNCC.setBounds(200, 30, 220, 30);

        btnAddNCC.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnAddNCC.setText("Thêm");
        add(btnAddNCC);
        btnAddNCC.setBounds(460, 30, 120, 30);

        btnFixNCC.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnFixNCC.setText("Sửa");
        add(btnFixNCC);
        btnFixNCC.setBounds(460, 130, 120, 29);

        bthDelNCC.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        bthDelNCC.setText("Xóa");
        bthDelNCC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bthDelNCCActionPerformed(evt);
            }
        });
        add(bthDelNCC);
        bthDelNCC.setBounds(460, 180, 120, 29);

        btnReloadNCC.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnReloadNCC.setText("Tải lại");
        add(btnReloadNCC);
        btnReloadNCC.setBounds(860, 350, 120, 30);

        btnFindNCC.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnFindNCC.setText("Tìm");
        btnFindNCC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindNCCActionPerformed(evt);
            }
        });
        add(btnFindNCC);
        btnFindNCC.setBounds(460, 80, 120, 29);

        tblListNCC.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tblListNCC.setForeground(new java.awt.Color(0, 102, 255));
        tblListNCC.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã NCC", "Tên", "Số điện thoại", "Số tài khoản", "Địa chỉ", "Số tài khoản", "Tình trạng"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblListNCC.setRowSelectionAllowed(false);
        tblListNCC.setSelectionBackground(new java.awt.Color(0, 51, 255));
        jScrollPane1.setViewportView(tblListNCC);

        add(jScrollPane1);
        jScrollPane1.setBounds(2, 390, 1000, 430);

        lbMailNCC.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbMailNCC.setText("Tình Trạng");
        add(lbMailNCC);
        lbMailNCC.setBounds(80, 280, 90, 30);

        lbListNCC.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbListNCC.setText("Danh sách nhà cung cấp");
        add(lbListNCC);
        lbListNCC.setBounds(20, 330, 200, 50);

        lbMailNCC1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbMailNCC1.setText("Số tài khoản");
        add(lbMailNCC1);
        lbMailNCC1.setBounds(70, 230, 100, 30);

        txtMailNCC1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMailNCC1ActionPerformed(evt);
            }
        });
        add(txtMailNCC1);
        txtMailNCC1.setBounds(200, 180, 220, 30);
    }// </editor-fold>//GEN-END:initComponents

    private void txtSĐTNCCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSĐTNCCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSĐTNCCActionPerformed

    private void txtAddressNCCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAddressNCCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAddressNCCActionPerformed

    private void txtNameNCCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameNCCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameNCCActionPerformed

    private void txtMailNCCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMailNCCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMailNCCActionPerformed

    private void txtIDNCCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDNCCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDNCCActionPerformed

    private void bthDelNCCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bthDelNCCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bthDelNCCActionPerformed

    private void btnFindNCCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindNCCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFindNCCActionPerformed

    private void txtMailNCC1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMailNCC1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMailNCC1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bthDelNCC;
    private javax.swing.JButton btnAddNCC;
    private javax.swing.JButton btnFindNCC;
    private javax.swing.JButton btnFixNCC;
    private javax.swing.JButton btnReloadNCC;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbAddressNCC;
    private javax.swing.JLabel lbIDNCC;
    private javax.swing.JLabel lbInfNCC;
    private javax.swing.JLabel lbListNCC;
    private javax.swing.JLabel lbMailNCC;
    private javax.swing.JLabel lbMailNCC1;
    private javax.swing.JLabel lbNameNCC;
    private javax.swing.JLabel lbSĐTNCC;
    private javax.swing.JTable tblListNCC;
    private javax.swing.JTextField txtAddressNCC;
    private javax.swing.JTextField txtIDNCC;
    private javax.swing.JTextField txtMailNCC;
    private javax.swing.JTextField txtMailNCC1;
    private javax.swing.JTextField txtNameNCC;
    private javax.swing.JTextField txtSĐTNCC;
    // End of variables declaration//GEN-END:variables
}
