package GUI.Form;

import GUI.Form.Abstract.JTablePanel;

public class FormPhieuNhap extends JTablePanel {
    public FormPhieuNhap() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textMapn = new javax.swing.JTextField();
        textMancc = new javax.swing.JTextField();
        javax.swing.JLabel labelMapn = new javax.swing.JLabel();
        javax.swing.JLabel labelManv = new javax.swing.JLabel();
        javax.swing.JLabel labelMancc = new javax.swing.JLabel();
        textManv = new javax.swing.JTextField();
        javax.swing.JLabel labelNgaytao = new javax.swing.JLabel();
        textNgaytao = new javax.swing.JTextField();
        jLabelTtpn = new javax.swing.JLabel();
        textMahd1 = new javax.swing.JTextField();
        textMakh1 = new javax.swing.JTextField();
        textThanhtien1 = new javax.swing.JTextField();
        javax.swing.JLabel labelMapn1 = new javax.swing.JLabel();
        javax.swing.JLabel labelMasl1 = new javax.swing.JLabel();
        javax.swing.JLabel labelMasp1 = new javax.swing.JLabel();
        javax.swing.JLabel labelThanhtien1 = new javax.swing.JLabel();
        textManv1 = new javax.swing.JTextField();
        javax.swing.JLabel labelDongia1 = new javax.swing.JLabel();
        textNgaylap1 = new javax.swing.JTextField();
        javax.swing.JLabel labelTongtien = new javax.swing.JLabel();
        textTongtien = new javax.swing.JTextField();
        bntThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        bntXoa = new javax.swing.JButton();
        btnTim = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        jLabelCtpn = new javax.swing.JLabel();
        bntThem1 = new javax.swing.JButton();
        btnSua1 = new javax.swing.JButton();
        bntXoa1 = new javax.swing.JButton();
        btnTim1 = new javax.swing.JButton();
        btnRefresh1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableTtpn = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableCtpn = new javax.swing.JTable();

        setLayout(null);

        textMapn.setToolTipText("");
        add(textMapn);
        textMapn.setBounds(130, 50, 150, 22);

        textMancc.setToolTipText("");
        add(textMancc);
        textMancc.setBounds(130, 80, 150, 22);

        labelMapn.setText("Mã Phiếu Nhập");
        add(labelMapn);
        labelMapn.setBounds(20, 50, 160, 16);

        labelManv.setText("Mã Nhân Viên");
        add(labelManv);
        labelManv.setBounds(20, 110, 160, 16);

        labelMancc.setText("Mã Cung Cấp");
        add(labelMancc);
        labelMancc.setBounds(20, 80, 150, 16);

        textManv.setToolTipText("");
        add(textManv);
        textManv.setBounds(130, 110, 150, 22);

        labelNgaytao.setText("Ngày Tạo");
        add(labelNgaytao);
        labelNgaytao.setBounds(20, 140, 88, 16);

        textNgaytao.setToolTipText("");
        textNgaytao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textNgaytaoActionPerformed(evt);
            }
        });
        add(textNgaytao);
        textNgaytao.setBounds(130, 140, 150, 22);

        jLabelTtpn.setText("THÔNG TIN PHIẾU NHẬP");
        add(jLabelTtpn);
        jLabelTtpn.setBounds(130, 20, 240, 16);

        textMahd1.setToolTipText("");
        add(textMahd1);
        textMahd1.setBounds(730, 50, 150, 22);

        textMakh1.setToolTipText("");
        add(textMakh1);
        textMakh1.setBounds(730, 80, 150, 22);

        textThanhtien1.setToolTipText("");
        textThanhtien1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textThanhtien1ActionPerformed(evt);
            }
        });
        add(textThanhtien1);
        textThanhtien1.setBounds(730, 170, 150, 22);

        labelMapn1.setText("Mã Phiếu Nhập");
        add(labelMapn1);
        labelMapn1.setBounds(620, 50, 170, 16);

        labelMasl1.setText("Số Lượng");
        add(labelMasl1);
        labelMasl1.setBounds(620, 110, 88, 16);

        labelMasp1.setText("Mã Sản Phẩm");
        add(labelMasp1);
        labelMasp1.setBounds(620, 80, 180, 16);

        labelThanhtien1.setText("Thành Tiền");
        add(labelThanhtien1);
        labelThanhtien1.setBounds(620, 170, 88, 16);

        textManv1.setToolTipText("");
        add(textManv1);
        textManv1.setBounds(730, 110, 150, 22);

        labelDongia1.setText("Đơn Giá");
        add(labelDongia1);
        labelDongia1.setBounds(620, 140, 88, 16);

        textNgaylap1.setToolTipText("");
        textNgaylap1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textNgaylap1ActionPerformed(evt);
            }
        });
        add(textNgaylap1);
        textNgaylap1.setBounds(730, 140, 150, 22);

        labelTongtien.setText("Tổng Tiền");
        add(labelTongtien);
        labelTongtien.setBounds(20, 170, 88, 16);

        textTongtien.setToolTipText("");
        textTongtien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textTongtienActionPerformed(evt);
            }
        });
        add(textTongtien);
        textTongtien.setBounds(130, 170, 150, 22);

        bntThem.setText("Thêm");
        bntThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntThemActionPerformed(evt);
            }
        });
        add(bntThem);
        bntThem.setBounds(290, 50, 80, 22);

        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });
        add(btnSua);
        btnSua.setBounds(290, 80, 80, 22);

        bntXoa.setText("Xóa");
        bntXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntXoaActionPerformed(evt);
            }
        });
        add(bntXoa);
        bntXoa.setBounds(290, 110, 80, 22);

        btnTim.setText("Tìm");
        btnTim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimActionPerformed(evt);
            }
        });
        add(btnTim);
        btnTim.setBounds(290, 140, 80, 22);

        btnRefresh.setText("Tải Lại");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });
        add(btnRefresh);
        btnRefresh.setBounds(290, 170, 80, 22);

        jLabelCtpn.setText("CHI TIẾT PHIẾU NHẬP");
        add(jLabelCtpn);
        jLabelCtpn.setBounds(730, 20, 240, 16);

        bntThem1.setText("Thêm");
        bntThem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntThem1ActionPerformed(evt);
            }
        });
        add(bntThem1);
        bntThem1.setBounds(890, 50, 80, 22);

        btnSua1.setText("Sửa");
        btnSua1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSua1ActionPerformed(evt);
            }
        });
        add(btnSua1);
        btnSua1.setBounds(890, 80, 80, 22);

        bntXoa1.setText("Xóa");
        bntXoa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntXoa1ActionPerformed(evt);
            }
        });
        add(bntXoa1);
        bntXoa1.setBounds(890, 110, 80, 22);

        btnTim1.setText("Tìm");
        btnTim1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTim1ActionPerformed(evt);
            }
        });
        add(btnTim1);
        btnTim1.setBounds(890, 140, 80, 22);

        btnRefresh1.setText("Tải Lại");
        btnRefresh1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefresh1ActionPerformed(evt);
            }
        });
        add(btnRefresh1);
        btnRefresh1.setBounds(890, 170, 80, 22);

        jTableTtpn.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã Phiếu Nhập", "Mã Cung Cấp", "Mã Nhân Viên", "Ngày Tạo", "Tổng Tiền"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableTtpn.setColumnSelectionAllowed(true);
        jTableTtpn.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTableTtpn);

        add(jScrollPane1);
        jScrollPane1.setBounds(10, 250, 980, 300);

        jTableCtpn.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã Phiếu Nhập", "Mã Sản Phẩm", "Số Lượng", "Đơn Giá", "Thành Tiền"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableCtpn.setColumnSelectionAllowed(true);
        jTableCtpn.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(jTableCtpn);

        add(jScrollPane2);
        jScrollPane2.setBounds(10, 560, 980, 250);
    }// </editor-fold>//GEN-END:initComponents

    private void textNgaytaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNgaytaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textNgaytaoActionPerformed

    private void textThanhtien1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textThanhtien1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textThanhtien1ActionPerformed

    private void textNgaylap1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNgaylap1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textNgaylap1ActionPerformed

    private void textTongtienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textTongtienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textTongtienActionPerformed

    private void bntThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntThemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bntThemActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSuaActionPerformed

    private void bntXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntXoaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bntXoaActionPerformed

    private void btnTimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTimActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void bntThem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntThem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bntThem1ActionPerformed

    private void btnSua1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSua1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSua1ActionPerformed

    private void bntXoa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntXoa1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bntXoa1ActionPerformed

    private void btnTim1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTim1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTim1ActionPerformed

    private void btnRefresh1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefresh1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRefresh1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntThem;
    private javax.swing.JButton bntThem1;
    private javax.swing.JButton bntXoa;
    private javax.swing.JButton bntXoa1;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnRefresh1;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnSua1;
    private javax.swing.JButton btnTim;
    private javax.swing.JButton btnTim1;
    private javax.swing.JLabel jLabelCtpn;
    private javax.swing.JLabel jLabelTtpn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableCtpn;
    private javax.swing.JTable jTableTtpn;
    private javax.swing.JTextField textMahd1;
    private javax.swing.JTextField textMakh1;
    private javax.swing.JTextField textMancc;
    private javax.swing.JTextField textManv;
    private javax.swing.JTextField textManv1;
    private javax.swing.JTextField textMapn;
    private javax.swing.JTextField textNgaylap1;
    private javax.swing.JTextField textNgaytao;
    private javax.swing.JTextField textThanhtien1;
    private javax.swing.JTextField textTongtien;
    // End of variables declaration//GEN-END:variables
}
