package GUI.Form;


import GUI.Form.Abstract.JTablePanel;

public class FormSanPham extends JTablePanel {
    public FormSanPham() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelQlsp = new javax.swing.JLabel();
        jLabelMota = new javax.swing.JLabel();
        jLabelMaloai = new javax.swing.JLabel();
        jLabelMancc = new javax.swing.JLabel();
        jLabelTensp = new javax.swing.JLabel();
        jLabelDongia = new javax.swing.JLabel();
        jLabelDonvi = new javax.swing.JLabel();
        jLabelSoluong = new javax.swing.JLabel();
        labelMasp = new javax.swing.JLabel();
        bntAnh = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jPanelAnh = new javax.swing.JPanel();
        jButton7 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        textMota = new javax.swing.JTextArea();
        textMasp = new javax.swing.JTextField();
        textTensp = new javax.swing.JTextField();
        textDongia = new javax.swing.JTextField();
        textMancc = new javax.swing.JComboBox<>();
        textSoluong = new javax.swing.JTextField();
        textDonvi = new javax.swing.JTextField();
        textMaloai = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableQlsp = new javax.swing.JTable();

        setLayout(null);

        jLabelQlsp.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabelQlsp.setText("QUẢN LÝ SẢN PHẨM");
        add(jLabelQlsp);
        jLabelQlsp.setBounds(390, 20, 280, 20);

        jLabelMota.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelMota.setText("Mô Tả");
        add(jLabelMota);
        jLabelMota.setBounds(40, 170, 100, 20);

        jLabelMaloai.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelMaloai.setText("Mã Loại");
        add(jLabelMaloai);
        jLabelMaloai.setBounds(490, 200, 80, 20);

        jLabelMancc.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelMancc.setText("Mã NCC");
        add(jLabelMancc);
        jLabelMancc.setBounds(490, 250, 100, 20);

        jLabelTensp.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelTensp.setText("Tên Sản Phẩm");
        add(jLabelTensp);
        jLabelTensp.setBounds(40, 120, 120, 20);

        jLabelDongia.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelDongia.setText("Đơn Giá");
        add(jLabelDongia);
        jLabelDongia.setBounds(490, 70, 80, 20);

        jLabelDonvi.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelDonvi.setText("Đơn Vị");
        add(jLabelDonvi);
        jLabelDonvi.setBounds(490, 120, 80, 20);

        jLabelSoluong.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelSoluong.setText("Số Lượng");
        add(jLabelSoluong);
        jLabelSoluong.setBounds(490, 160, 80, 20);

        labelMasp.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelMasp.setText("Mã Sản Phẩm");
        add(labelMasp);
        labelMasp.setBounds(40, 70, 120, 20);

        bntAnh.setText("Chọn Ảnh");
        bntAnh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntAnhActionPerformed(evt);
            }
        });
        add(bntAnh);
        bntAnh.setBounds(800, 260, 130, 22);

        jButton2.setText("Thêm");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2);
        jButton2.setBounds(160, 340, 80, 22);

        jButton3.setText("Xóa");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        add(jButton3);
        jButton3.setBounds(270, 340, 80, 22);

        jButton5.setText("Sửa");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        add(jButton5);
        jButton5.setBounds(390, 340, 80, 22);

        btnRefresh.setText("Tải Lại");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });
        add(btnRefresh);
        btnRefresh.setBounds(510, 340, 80, 22);

        jButton6.setText("Xuất");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        add(jButton6);
        jButton6.setBounds(630, 340, 80, 22);

        jPanelAnh.setBackground(new java.awt.Color(255, 255, 255));
        jPanelAnh.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        javax.swing.GroupLayout jPanelAnhLayout = new javax.swing.GroupLayout(jPanelAnh);
        jPanelAnh.setLayout(jPanelAnhLayout);
        jPanelAnhLayout.setHorizontalGroup(
            jPanelAnhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 172, Short.MAX_VALUE)
        );
        jPanelAnhLayout.setVerticalGroup(
            jPanelAnhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 172, Short.MAX_VALUE)
        );

        add(jPanelAnh);
        jPanelAnh.setBounds(780, 70, 180, 180);

        jButton7.setText("Nhập");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        add(jButton7);
        jButton7.setBounds(750, 340, 80, 22);

        textMota.setColumns(20);
        textMota.setRows(5);
        jScrollPane2.setViewportView(textMota);

        add(jScrollPane2);
        jScrollPane2.setBounds(150, 170, 310, 110);

        textMasp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textMaspActionPerformed(evt);
            }
        });
        add(textMasp);
        textMasp.setBounds(150, 70, 310, 30);
        add(textTensp);
        textTensp.setBounds(150, 120, 310, 30);
        add(textDongia);
        textDongia.setBounds(570, 70, 160, 30);

        textMancc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Chọn NCC", "Đại Lý Cà Phê", "Đại Lý Đường", "Đại Lý Sữa", "Đại Lý Kem", "Đại Lý Nước", "Đại Lý Đá", "Đại Lý Giấy In Bill", "Đại Lý Cà Phê Hạt", "Đại Lý Bao Đựng Ly", "Đại Lý Hộp Nhựa" }));
        add(textMancc);
        textMancc.setBounds(570, 250, 160, 30);
        add(textSoluong);
        textSoluong.setBounds(570, 160, 160, 30);
        add(textDonvi);
        textDonvi.setBounds(570, 120, 160, 30);

        textMaloai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Chọn Loại", "CAFE", "Nước Ngọt", "Matcha\t", "Cà Phê Phin", "Cà Phê Pha Máy", "Cà Phê Nguyên Chất", "Cà Phê Latte", "Capuchino", "Matchiato" }));
        add(textMaloai);
        textMaloai.setBounds(570, 200, 160, 30);

        jTableQlsp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã Sản Phẩm", "Tên Sản Phẩm", "Mã Loại", "Mã NCC", "Hình Ảnh", "Đơn Giá", "Đơn Vị", "Số lượng", "Mô Tả"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableQlsp.setColumnSelectionAllowed(true);
        jTableQlsp.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTableQlsp);

        add(jScrollPane1);
        jScrollPane1.setBounds(12, 390, 980, 420);
    }// </editor-fold>//GEN-END:initComponents

    private void bntAnhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntAnhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bntAnhActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void textMaspActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textMaspActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textMaspActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntAnh;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabelDongia;
    private javax.swing.JLabel jLabelDonvi;
    private javax.swing.JLabel jLabelMaloai;
    private javax.swing.JLabel jLabelMancc;
    private javax.swing.JLabel jLabelMota;
    private javax.swing.JLabel jLabelQlsp;
    private javax.swing.JLabel jLabelSoluong;
    private javax.swing.JLabel jLabelTensp;
    private javax.swing.JPanel jPanelAnh;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableQlsp;
    private javax.swing.JLabel labelMasp;
    private javax.swing.JTextField textDongia;
    private javax.swing.JTextField textDonvi;
    private javax.swing.JComboBox<String> textMaloai;
    private javax.swing.JComboBox<String> textMancc;
    private javax.swing.JTextField textMasp;
    private javax.swing.JTextArea textMota;
    private javax.swing.JTextField textSoluong;
    private javax.swing.JTextField textTensp;
    // End of variables declaration//GEN-END:variables
}
