package Utils;

import java.sql.*;

public class MyDBConnection {
    String Host;
    String Database;
    String UserName;
    String Password;
    
    Connection connection = null;

    public MyDBConnection(String Host, String Database, String UserName, String Password) {
        this.Host = Host;
        this.Database = Database;
        this.UserName = UserName;
        this.Password = Password;
    }     
     
    public void driverTest() throws ClassNotFoundException {
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
        } catch (ClassNotFoundException e) {
            throw new ClassNotFoundException("MySQL Driver JDBC not found");
        }
    }

    public boolean isClosed() throws SQLException {
        return connection == null || connection.isClosed();
    }

    public Connection getConnection() throws SQLException, ClassNotFoundException {
        if (isClosed()) {
            driverTest();
            String url = "jdbc:mysql://" + Host + ":3306/" + Database
                            + "?autoReconnect=true&useSSL=false&useUnicode=true&characterEncoding=UTF-8";
            try {
                connection = DriverManager.getConnection(url, UserName, Password);
            } catch (SQLException e){
                throw new SQLException("Unable to connect MySQL server ! " + e);
            }
        }
        return connection;
    }

    public void setParameter(PreparedStatement statement, Object... parameters) {
        try {
            for (int i = 0; i < parameters.length; i++) {
                Object parameter = parameters[i];
                int index = i + 1;
                if (parameter == null) {
                    statement.setNull(index, Types.NULL);
                } else if (parameter instanceof String) {
                    statement.setString(index, (String) parameter);
                } else if (parameter instanceof Integer) {
                    statement.setInt(index, (Integer) parameter);
                } else if (parameter instanceof Timestamp) {
                    statement.setTimestamp(index, (Timestamp) parameter);
                } else if (parameter instanceof Date) {
                    statement.setDate(index, (Date) parameter);
                }
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    public ResultSet executeQuery(String sql, Object... parameters) throws SQLException, ClassNotFoundException {
        PreparedStatement statement = getConnection().prepareStatement(sql);
        setParameter(statement, parameters);
        return statement.executeQuery();
    }

    public int executeUpdate(String sql, Object... parameters) throws SQLException, ClassNotFoundException {
        PreparedStatement statement = getConnection().prepareStatement(sql);
        setParameter(statement, parameters);
        setAutoCommit(false);
        int result = statement.executeUpdate();
        commit();
        return result;
    }

    public ResultSet executeUpdate(String sql, int autoGeneratedKeys, Object... parameters) throws SQLException, ClassNotFoundException {
        PreparedStatement statement = getConnection().prepareStatement(sql, autoGeneratedKeys);
        setParameter(statement, parameters);
        setAutoCommit(false);
        statement.executeUpdate();
        ResultSet resultSet = statement.getGeneratedKeys();
        commit();
        return resultSet;
    }

    public void setAutoCommit(boolean b) throws SQLException {
        if (!isClosed())
            connection.setAutoCommit(b);
    }

    public void commit() throws SQLException {
        if (!isClosed())
            connection.commit();
    }

    public void rollback() {
        try {
            getConnection().rollback();
        } catch (SQLException | ClassNotFoundException e) {
            e.printStackTrace();
        }
    }
	
    public void close() throws SQLException {
        if (connection != null && !connection.isClosed()) {
            connection.close();
            connection = null;
        }       
    }    
}